export const PROJECTS_LIST_FETCH_IN_PROGRESS = 'PROJECTS_LIST_FETCH_IN_PROGRESS';
export const PROJECTS_LIST_FETCH_SUCCESS = 'PROJECTS_LIST_FETCH_SUCCESS';
export const PROJECTS_LIST_FETCH_ERROR = 'PROJECTS_LIST_FETCH_ERROR';

export const MINT_NFT_IN_PROGRESS = 'MINT_NFT_IN_PROGRESS';
export const MINT_NFT_SUCCESS = 'MINT_NFT_SUCCESS';
export const MINT_NFT_ERROR = 'MINT_NFT_ERROR';

export const MINT_REQUEST_FETCH_IN_PROGRESS = 'MINT_REQUEST_FETCH_IN_PROGRESS';
export const MINT_REQUEST_FETCH_SUCCESS = 'MINT_REQUEST_FETCH_SUCCESS';
export const MINT_REQUEST_FETCH_ERROR = 'MINT_REQUEST_FETCH_ERROR';

export const MINT_QUEUE_FETCH_IN_PROGRESS = 'MINT_QUEUE_FETCH_IN_PROGRESS';
export const MINT_QUEUE_FETCH_SUCCESS = 'MINT_QUEUE_FETCH_SUCCESS';
export const MINT_QUEUE_FETCH_ERROR = 'MINT_QUEUE_FETCH_ERROR';

export const NFT_FETCH_IN_PROGRESS = 'NFT_FETCH_IN_PROGRESS';
export const NFT_FETCH_SUCCESS = 'NFT_FETCH_SUCCESS';
export const NFT_FETCH_ERROR = 'NFT_FETCH_ERROR';

export const MINT_NFT_IN_PROGRESS_SET = 'MINT_NFT_IN_PROGRESS_SET';

export const NFT_CLAIM_STATUS_CHECK_IN_PROGRESS = 'NFT_CLAIM_STATUS_CHECK_IN_PROGRESS';
export const NFT_CLAIM_STATUS_CHECK_SUCCESS = 'NFT_CLAIM_STATUS_CHECK_SUCCESS';
export const NFT_CLAIM_STATUS_CHECK_ERROR = 'NFT_CLAIM_STATUS_CHECK_ERROR';
